#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: festival-spanish-voices
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el festival-spanish-voices para incluir divert.
# COPYRIGHT:
#  (C) 2013 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="festival-spanish-voices"

set -e

case ${1} in

	configure)
	;;

	*)

	ln -s /lib/systemd/system/festival.service /etc/systemd/system/festival-canaima.service
	echo "enlace listo"

	divert_festival /usr/share/festival/voices/spanish/JuntaDeAndalucia_es_sf_diphone/config/festival.scm.canaima /etc/festival.scm 
	echo "divert_fetival"

	divert_speek /usr/share/festival/voices/spanish/JuntaDeAndalucia_es_sf_diphone/config/speech-dispatcher.canaima /etc/default/speech-dispatcher

	echo "divert speek"

	update-alternatives --install /etc/speech-dispatcher/speechd.conf speech-dispatcher /usr/share/festival/voices/spanish/JuntaDeAndalucia_es_sf_diphone/spdconf/speechd.conf 20

	echo "update-alternatives"

	service speech-dispatcherd restart

esac


divert_festival() {

                dpkg-divert --package ${PKG} --add --divert $1 $2
                dpkg-divert --package  ${PKG} --list

}
divert_speek() {

                dpkg-divert --package ${PKG} --add --divert $1 $2
                dpkg-divert --package  ${PKG} --list     

}

#DEBHELPER#

exit 0
