#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: festival-spanish-voices
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el festival-spanish-voices para incluir divert.
# COPYRIGHT:
#  (C) 2011 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="festival-spanish-voices"

set -e

divertrm() {

	
       	dpkg-divert --package ${PKG} --remove --divert $1 $2
	echo "removido divert de ${PKG}"
	

}

# Divert the following files if no diversion exists already
# It is currentliy used to prevent the files collision between bash and
# dash: they both provide the files in the package.

divertrm /usr/share/festival-spanish-voices/festival.scm.canaima \
	 /etc/festival.scm 


rm /etc/systemd/system/festival-canaima.service
rm /lib/systemd/system/festival.service
rm /usr/local/bin/festival.sh
rm -rf /usr/share/festival/voices/spanish/*

#Borramos el ALTERNATIVE

update-alternatives --remove speech-dispatcher /etc/speech-dispatcherusr/speechd.conf


#DEBHELPER#

exit 0

